import type { RepairTicket, Product, User } from './types';

export const mockUser: User = {
  name: 'Admin User',
  email: 'admin@repairhub.com',
  avatar: 'https://i.pravatar.cc/150?u=admin@repairhub.com',
};

export const mockTickets: RepairTicket[] = [
  {
    id: '1',
    ticketNumber: 'RPR-2025-0001',
    customerId: 'cust-123',
    customerName: 'Alice Johnson',
    deviceType: 'Smartphone',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 13',
    issueDescription: 'Cracked screen after dropping the phone on concrete. The touch screen is unresponsive in the top right corner.',
    status: 'repairing',
    priority: 'high',
    estimatedCost: 180.00,
    finalCost: null,
    createdAt: '2024-07-20T10:00:00Z',
    updatedAt: '2024-07-22T14:30:00Z',
    estimatedCompletion: '2024-07-23T17:00:00Z',
  },
  {
    id: '2',
    ticketNumber: 'RPR-2025-0002',
    customerId: 'cust-124',
    customerName: 'Bob Williams',
    deviceType: 'Smartphone',
    deviceBrand: 'Samsung',
    deviceModel: 'Galaxy S22',
    issueDescription: 'Battery drains very quickly, does not last a full day even with light usage. Phone also gets hot while charging.',
    status: 'diagnosing',
    priority: 'normal',
    estimatedCost: 95.00,
    finalCost: null,
    createdAt: '2024-07-21T11:30:00Z',
    updatedAt: '2024-07-22T09:00:00Z',
    estimatedCompletion: '2024-07-24T12:00:00Z',
  },
  {
    id: '3',
    ticketNumber: 'RPR-2025-0003',
    customerId: 'cust-125',
    customerName: 'Charlie Brown',
    deviceType: 'Tablet',
    deviceBrand: 'Apple',
    deviceModel: 'iPad Air',
    issueDescription: 'Charging port is loose. The cable needs to be held at a specific angle to charge.',
    status: 'awaiting_parts',
    priority: 'normal',
    estimatedCost: 120.00,
    finalCost: null,
    createdAt: '2024-07-22T09:00:00Z',
    updatedAt: '2024-07-22T16:00:00Z',
    estimatedCompletion: '2024-07-28T17:00:00Z',
  },
  {
    id: '4',
    ticketNumber: 'RPR-2025-0004',
    customerId: 'cust-126',
    customerName: 'Diana Prince',
    deviceType: 'Smartphone',
    deviceBrand: 'Google',
    deviceModel: 'Pixel 6',
    issueDescription: 'Phone does not turn on. No response when plugging in the charger or holding the power button.',
    status: 'received',
    priority: 'urgent',
    estimatedCost: null,
    finalCost: null,
    createdAt: '2024-07-22T15:00:00Z',
    updatedAt: '2024-07-22T15:00:00Z',
    estimatedCompletion: null,
  },
    {
    id: '5',
    ticketNumber: 'RPR-2025-0005',
    customerId: 'cust-127',
    customerName: 'Ethan Hunt',
    deviceType: 'Smartphone',
    deviceBrand: 'OnePlus',
    deviceModel: '9 Pro',
    issueDescription: 'Rear camera glass is cracked, and photos are blurry. Main camera works, but ultrawide is affected.',
    status: 'ready',
    priority: 'low',
    estimatedCost: 85.00,
    finalCost: 85.00,
    createdAt: '2024-07-18T16:00:00Z',
    updatedAt: '2024-07-22T11:00:00Z',
    estimatedCompletion: '2024-07-22T11:00:00Z',
  },
  {
    id: '6',
    ticketNumber: 'RPR-2025-0006',
    customerId: 'cust-128',
    customerName: 'Fiona Glenanne',
    deviceType: 'Laptop',
    deviceBrand: 'Apple',
    deviceModel: 'MacBook Pro 14"',
    issueDescription: 'Water spill on keyboard. Some keys are not working correctly. Need a full diagnostic.',
    status: 'quality_check',
    priority: 'high',
    estimatedCost: 450.00,
    finalCost: null,
    createdAt: '2024-07-19T13:00:00Z',
    updatedAt: '2024-07-22T15:30:00Z',
    estimatedCompletion: '2024-07-22T18:00:00Z',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Stealth Armor Case for iPhone 15',
    slug: 'stealth-armor-case-iphone-15',
    category: 'Cases',
    description: 'Military-grade drop protection with a slim profile. Features a non-slip grip and responsive button covers.',
    price: 29.99,
    stockQuantity: 42,
    imageUrl: 'https://picsum.photos/seed/101/400/400',
    imageHint: 'phone case',
    isFeatured: true,
  },
  {
    id: 'prod-2',
    name: 'TurboCharge 65W GaN Charger',
    slug: 'turbocharge-65w-gan-charger',
    category: 'Chargers',
    description: 'Ultra-compact Gallium Nitride charger with two USB-C ports. Fast charge your phone, tablet, and laptop.',
    price: 45.50,
    stockQuantity: 25,
    imageUrl: 'https://picsum.photos/seed/102/400/400',
    imageHint: 'phone charger',
    isFeatured: true,
  },
  {
    id: 'prod-3',
    name: 'AuraSound Pro Wireless Earbuds',
    slug: 'aurasound-pro-wireless-earbuds',
    category: 'Audio',
    description: 'Active Noise Cancellation, 8-hour battery life, and a pocket-sized charging case. Crystal clear calls with 3-mic system.',
    price: 89.00,
    stockQuantity: 15,
    imageUrl: 'https://picsum.photos/seed/103/400/400',
    imageHint: 'wireless headphones',
    isFeatured: true,
  },
  {
    id: 'prod-4',
    name: 'Endura T20 Power Bank 20000mAh',
    slug: 'endura-t20-power-bank',
    category: 'Power Banks',
    description: 'High-capacity power bank to charge your phone up to 4 times. Features dual USB-A and one USB-C port.',
    price: 39.99,
    stockQuantity: 30,
    imageUrl: 'https://picsum.photos/seed/104/400/400',
    imageHint: 'power bank',
    isFeatured: false,
  },
  {
    id: 'prod-5',
    name: 'CrystalShield Tempered Glass',
    slug: 'crystalshield-tempered-glass',
    category: 'Screen Protectors',
    description: '9H hardness tempered glass screen protector with oleophobic coating. Easy installation kit included.',
    price: 14.99,
    stockQuantity: 150,
    imageUrl: 'https://picsum.photos/seed/105/400/400',
    imageHint: 'screen protector',
    isFeatured: false,
  },
  {
    id: 'prod-6',
    name: 'ChronoFit Smartwatch Series 5',
    slug: 'chronofit-smartwatch-series-5',
    category: 'Wearables',
    description: 'Track your fitness, receive notifications, and more with this stylish smartwatch. Compatible with iOS and Android.',
    price: 129.99,
    stockQuantity: 18,
    imageUrl: 'https://picsum.photos/seed/106/400/400',
    imageHint: 'smartwatch',
    isFeatured: false,
  },
];
