
import type { RepairTicket, Product, User } from './types';

export const mockUser: User = {
  name: 'Admin User',
  email: 'admin@repairhub.com',
  avatar: 'https://i.pravatar.cc/150?u=admin@repairhub.com',
};

export const mockTickets: RepairTicket[] = [
  {
    id: '1',
    ticketNumber: 'RPR-2025-0001',
    customerId: 'cust-123',
    customerName: 'Alice Johnson',
    deviceType: 'Smartphone',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 13',
    issueDescription: 'Cracked screen after dropping the phone on concrete. The touch screen is unresponsive in the top right corner.',
    status: 'repairing',
    priority: 'high',
    estimatedCost: 18000.00,
    finalCost: null,
    createdAt: '2024-07-20T10:00:00Z',
    updatedAt: '2024-07-22T14:30:00Z',
    estimatedCompletion: '2024-07-23T17:00:00Z',
  },
  {
    id: '2',
    ticketNumber: 'RPR-2025-0002',
    customerId: 'cust-124',
    customerName: 'Bob Williams',
    deviceType: 'Smartphone',
    deviceBrand: 'Samsung',
    deviceModel: 'Galaxy S22',
    issueDescription: 'Battery drains very quickly, does not last a full day even with light usage. Phone also gets hot while charging.',
    status: 'diagnosing',
    priority: 'normal',
    estimatedCost: 9500.00,
    finalCost: null,
    createdAt: '2024-07-21T11:30:00Z',
    updatedAt: '2024-07-22T09:00:00Z',
    estimatedCompletion: '2024-07-24T12:00:00Z',
  },
  {
    id: '3',
    ticketNumber: 'RPR-2025-0003',
    customerId: 'cust-125',
    customerName: 'Charlie Brown',
    deviceType: 'Tablet',
    deviceBrand: 'Apple',
    deviceModel: 'iPad Air',
    issueDescription: 'Charging port is loose. The cable needs to be held at a specific angle to charge.',
    status: 'awaiting_parts',
    priority: 'normal',
    estimatedCost: 12000.00,
    finalCost: null,
    createdAt: '2024-07-22T09:00:00Z',
    updatedAt: '2024-07-22T16:00:00Z',
    estimatedCompletion: '2024-07-28T17:00:00Z',
  },
  {
    id: '4',
    ticketNumber: 'RPR-2025-0004',
    customerId: 'cust-126',
    customerName: 'Diana Prince',
    deviceType: 'Smartphone',
    deviceBrand: 'Google',
    deviceModel: 'Pixel 6',
    issueDescription: 'Phone does not turn on. No response when plugging in the charger or holding the power button.',
    status: 'received',
    priority: 'urgent',
    estimatedCost: null,
    finalCost: null,
    createdAt: '2024-07-22T15:00:00Z',
    updatedAt: '2024-07-22T15:00:00Z',
    estimatedCompletion: null,
  },
    {
    id: '5',
    ticketNumber: 'RPR-2025-0005',
    customerId: 'cust-127',
    customerName: 'Ethan Hunt',
    deviceType: 'Smartphone',
    deviceBrand: 'OnePlus',
    deviceModel: '9 Pro',
    issueDescription: 'Rear camera glass is cracked, and photos are blurry. Main camera works, but ultrawide is affected.',
    status: 'ready',
    priority: 'low',
    estimatedCost: 8500.00,
    finalCost: 8500.00,
    createdAt: '2024-07-18T16:00:00Z',
    updatedAt: '2024-07-22T11:00:00Z',
    estimatedCompletion: '2024-07-22T11:00:00Z',
  },
  {
    id: '6',
    ticketNumber: 'RPR-2025-0006',
    customerId: 'cust-128',
    customerName: 'Fiona Glenanne',
    deviceType: 'Laptop',
    deviceBrand: 'Apple',
    deviceModel: 'MacBook Pro 14"',
    issueDescription: 'Water spill on keyboard. Some keys are not working correctly. Need a full diagnostic.',
    status: 'quality_check',
    priority: 'high',
    estimatedCost: 45000.00,
    finalCost: null,
    createdAt: '2024-07-19T13:00:00Z',
    updatedAt: '2024-07-22T15:30:00Z',
    estimatedCompletion: '2024-07-22T18:00:00Z',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-2',
    name: 'Carbon Fiber Shield Case for Galaxy S23',
    slug: 'carbon-fiber-shield-case-s23',
    category: 'Phone Cases',
    description: 'Ultra-thin, lightweight case with a sliding camera cover for privacy and lens protection. Features a sleek carbon fiber finish for superior drop protection.',
    price: 3500.00,
    stockQuantity: 75,
    imageUrl: 'https://picsum.photos/seed/galaxy-case-2/400/400',
    imageHint: 'camera cover',
    isFeatured: true,
  },
  {
    id: 'prod-4',
    name: 'Volta-Charge 100W PD Station',
    slug: 'volta-charge-100w-pd-station',
    category: 'Chargers',
    description: 'Charge up to 4 devices simultaneously. Perfect for laptops, phones, and tablets with Power Delivery.',
    price: 8000.00,
    stockQuantity: 40,
    imageUrl: 'https://picsum.photos/seed/102/400/400',
    imageHint: 'charging station',
    isFeatured: true,
  },
  {
    id: 'prod-3',
    name: 'Flow-State Pro Wireless Earphones',
    slug: 'flow-state-pro-earphones',
    category: 'Audio',
    description: 'Immersive sound with adaptive noise cancellation. Up to 30 hours of listening time with charging case.',
    price: 12500.00,
    stockQuantity: 30,
    imageUrl: 'https://picsum.photos/seed/103/400/400',
    imageHint: 'wireless earphones',
    isFeatured: true,
  },
  {
    id: 'prod-10',
    name: 'Mag-Lock Car Vent Mount',
    slug: 'mag-lock-car-vent-mount',
    category: 'Accessories',
    description: 'Securely mount your phone in your car with this strong magnetic vent holder. Adjustable and easy to install.',
    price: 2800.00,
    stockQuantity: 110,
    imageUrl: 'https://picsum.photos/seed/110/400/400',
    imageHint: 'car mount',
    isFeatured: false,
  },
  {
    id: 'prod-5',
    name: 'RhinoGlass Screen Protector for iPhone 15',
    slug: 'rhinoglass-screen-protector-iphone-15',
    category: 'Screen Protectors',
    description: '9H hardness ballistic glass for ultimate scratch and impact protection. Includes easy alignment tool.',
    price: 2500.00,
    stockQuantity: 200,
    imageUrl: 'https://picsum.photos/seed/105/400/400',
    imageHint: 'screen protector',
    isFeatured: false,
  },
  {
    id: 'prod-11',
    name: 'Grip-Ring Phone Holder & Stand',
    slug: 'grip-ring-phone-holder-stand',
    category: 'Accessories',
    description: 'A versatile ring that provides a secure grip on your phone and doubles as a kickstand for hands-free viewing.',
    price: 1500.00,
    stockQuantity: 150,
    imageUrl: 'https://picsum.photos/seed/111/400/400',
    imageHint: 'phone ring',
    isFeatured: false,
  },
];

    
